framework:
    workflows:
        # Workflow pour la gestion des événements
        event:
            type: state_machine
            supports:
                - App\Entity\Event
            initial_marking: CREATED
            marking_store:
                type: method
                property: state
            places:
                - CREATED
                - PUBLISHED
                - OPEN
                - CLOSED
                - ONGOING
                - FINISHED
                - CANCELED
                - ARCHIVED
            transitions:
                publish:
                    from: CREATED
                    to: PUBLISHED
                open_regs:
                    from: PUBLISHED
                    to: OPEN
                close_regs:
                    from: OPEN
                    to: CLOSED
                start:
                    from: CLOSED
                    to: ONGOING
                finish:
                    from: ONGOING
                    to: FINISHED
                cancel:
                    from: [CREATED, PUBLISHED, OPEN, CLOSED, ONGOING]
                    to: CANCELED
                archive:
                    from: [FINISHED, CANCELED]
                    to: ARCHIVED

        # Workflow pour la gestion des inscriptions des participants
        participation:
            type: state_machine
            supports:
                - App\Entity\Registration
            initial_marking: REGISTERED
            marking_store:
                type: method
                property: workflowState
            places:
                - REGISTERED
                - CANCELED
                - NOTIFIED
            transitions:
                register: # Transition "technique" pour déclencher entered.REGISTERED
                    from: REGISTERED
                    to: REGISTERED
                cancel:
                    from: [ REGISTERED, NOTIFIED ]
                    to: CANCELED
                notify:
                    from: REGISTERED
                    to: NOTIFIED
                restore_from_cancel:
                    from: CANCELED
                    to: REGISTERED
                restore_from_notify:
                    from: NOTIFIED
                    to: REGISTERED

